service: microproject

frameworkVersion: ">=1.27.2 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get
  